# Generated by Django 3.2.6 on 2021-08-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_user_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='status',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
