# Generated by Django 3.2.6 on 2021-08-13 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatroom_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='status',
            new_name='timestamp',
        ),
    ]
