# Generated by Django 3.2.6 on 2021-08-19 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20210820_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='settings_message',
            field=models.CharField(choices=[('all', 'Все'), ('friends', 'Только друзья')], default='all', max_length=255, verbose_name='Кто мне может отправлять сообщения?'),
        ),
    ]
