# Generated by Django 3.2.6 on 2021-08-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_user_settings_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatroom',
            options={'ordering': ('-timestamp',), 'verbose_name': 'Беседа', 'verbose_name_plural': 'Беседы'},
        ),
        migrations.AddField(
            model_name='chatroom',
            name='image',
            field=models.ImageField(default='chat_room_image/default.jpg', upload_to='chat_room_image', verbose_name='Фотография'),
        ),
    ]
