# Generated by Django 3.2.6 on 2021-08-22 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_chatroom_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='chat.user', verbose_name='Создатель беседы'),
            preserve_default=False,
        ),
    ]
