# Generated by Django 3.2.6 on 2021-08-23 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_auto_20210824_0044'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Friends',
            new_name='Friend',
        ),
    ]
