# Generated by Django 3.2.6 on 2021-08-23 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_rename_friends_friend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='status',
            field=models.CharField(choices=[('request', 'Запрос в друзья'), ('friend', 'Друзья'), ('subscriber', 'Подписчик')], default='request', max_length=255, verbose_name='Статус'),
        ),
    ]
