# Generated by Django 3.2.6 on 2021-08-23 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_alter_friend_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friends',
        ),
    ]
