# Generated by Django 3.2.6 on 2021-08-24 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_remove_user_friends'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friend',
            options={'verbose_name': 'Друг', 'verbose_name_plural': 'Друзья'},
        ),
        migrations.AlterField(
            model_name='friend',
            name='user_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь 1'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='user_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь 2'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='user_image/default.jpeg', upload_to='user_image', verbose_name='Фотография'),
        ),
    ]
