# Generated by Django 3.2.6 on 2021-08-27 15:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0020_privatechatroom_privatechatroommessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatechatroom',
            name='users',
            field=models.ManyToManyField(related_name='private_users', to=settings.AUTH_USER_MODEL, verbose_name='Участники чата'),
        ),
    ]
